Frida errors colors
FridaEriksson95/minesweeper pull request #24
Opened 2024-10-27 14:24 UTC by FridaEriksson95

2024-10-27 20:43 UTC, magnfreid submitted a review, later dismissed
Kolla gärna på rad 218 i Game-klassen. Kraschar just nu när man ska börja spela i 2-player

2024-10-27 20:43 UTC, magnfreid commented on src/Game.java
> -        board = new Board(size, bombs);
Ska denna rad verkligen bort? Får en krasch när jag försöker starta 2-player för att this.board är null

2024-10-27 22:04 UTC, magnfreid requested changes
Testar att göra en review. Kolla i Game-klassen rad 217-218

2024-10-27 22:04 UTC, magnfreid commented on src/Game.java
>          }
```suggestion
board = new Board(size, bombs);
}
```

2024-10-27 22:04 UTC, magnfreid commented on src/Game.java
>          }
Tror att denna rad försvann av misstag eftersom det kraschar nu när man startar 2-player och this.board är null

2024-10-28 11:38 UTC, magnfreid approved these changes

2024-10-28 11:54 UTC, BumBaZo86 reviewed
merge

2024-10-28 11:55 UTC, merged